### ISSUE TITLE
Alpha is not valid in 2012b

### ISSUE THREAD

**Issue by korymath** [korymath/runkeeper-testing#3]

**Comment by kylemath** [comment]
I got the new matlab, plot looks great,
Inline image 1
![image](https://cloud.githubusercontent.com/assets/3662613/15546399/03ccceea-225d-11e6-92ef-69bca939e36b.png)

but I am worried that the scatter dots are moving away from the line in some cases,
perhaps they are being plotted at the speed not the smoothed speed,

**Comment by korymath** [comment]
![example-compare-new](https://cloud.githubusercontent.com/assets/178099/15546491/61a63736-225d-11e6-82c2-663ec0098c69.png)

**Comment by korymath** [comment]
Focus on readability. 

But, I see what you mean... the data points don't 'really' correspond to the data labels,... thanks to the data smoothing... this can be seen here: 

![screen shot 2016-05-25 at 9 46 06 am](https://cloud.githubusercontent.com/assets/178099/15546558/952322ae-225d-11e6-92e6-6503f4da37be.png)

**Comment by korymath** [comment]
So now, we have the label with one value and the marker at another value... which is true?

**Comment by kylemath** [comment]
no the dots are correct now, 14 seconds is .233 of a minute

**Comment by korymath** [comment]
Okay, working on splits.

**Comment by korymath** [comment]
Finished splits... see the new commit
